name: Create IPA Packages

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "URL to the decrypted TikTok IPA file"
        default: ""
        required: true
        type: string
      tweak_url:
        description: "URL to the Doux tweak file (.deb)"
        default: ""
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      - name: Hide Sensitive Inputs
        uses: levibostian/action-hide-sensitive-inputs@v1

      - name: Download and Validate IPA
        run: |
          wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/tiktok.ipa
          file_type=$(file --mime-type -b ${{ github.workspace }}/tiktok.ipa)
          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Download and Validate Tweak
        run: |
          wget "${{ inputs.tweak_url }}" --no-verbose -O ${{ github.workspace }}/doux.deb
          file_type=$(file --mime-type -b ${{ github.workspace }}/doux.deb)
          if [[ "$file_type" != "application/vnd.debian.binary-package" ]]; then
            echo "::error::Validation failed: The file is not a valid DEB file. Detected type: $file_type."
            exit 1
          fi

      - name: Setup insert-dylib
        run: |
          git clone https://github.com/Tyilo/insert_dylib.git
          xcrun clang -x c -arch arm64 ./insert_dylib/insert_dylib/main.c -I/usr/include/ -o insert-dylib
          sudo mv insert-dylib /usr/local/bin/
          sudo chmod +x /usr/local/bin/insert-dylib

      - name: Setup ivinject
        run: |
          git clone https://github.com/whoeevee/ivinject.git
          cp -r ./ivinject/KnownFrameworks ~/.ivinject
          wget https://github.com/whoeevee/ivinject/releases/download/first/ivinject-arm64
          sudo mv ivinject-arm64 /usr/local/bin/
          sudo chmod +x /usr/local/bin/ivinject-arm64

      - name: Setup ipapatch
        run: |
          wget https://github.com/asdfzxcvbn/ipapatch/releases/download/v2.1.0/ipapatch.macos-arm64
          sudo mv ipapatch.macos-arm64 /usr/local/bin/ipapatch
          sudo chmod +x /usr/local/bin/ipapatch

      - name: Create Doux Package
        run: |
          ivinject-arm64 tiktok.ipa TikTok-Doux.ipa \
            -i doux.deb \
            -s - -d --level Optimal

      - name: Create Patched Package
        run: ipapatch -input TikTok-Doux.ipa -output TikTok-Doux-patched.ipa
    
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2.0.1
        with:
          tag_name: doux-${{ github.run_number }}
          name: TikTok Doux (${{ github.run_number }})
          files: |
            TikTok-Doux.ipa 
            TikTok-Doux-patched.ipa
          draft: true

      - name: Output Release URL
        run: |
          echo "::notice::Release available at: https://github.com/${{ github.repository }}/releases"
